apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-kgjl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nmvo-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-kgjl@sha256:268c1cf6e9e612690a703339d835a655ae8e72c1b1b80051379062874b83012e
        name: my-python
        resources: {}
status: {}
